### ISSUE TITLE
Post unable to update when using custom template

### ISSUE THREAD

**Issue by yahsaves** [mohamdio/wp-templater#2]
This looks like a great php script! Unfortunately I can not get it to work.

I'm using wordpress version 5.1, and when I select the custom template from the post metabox the post fails to update. It doesn't give me any other errors than "update failed". 

I put the source Templater file as well as the logic I use to call it in php files located in the top level directory of my plugin. 

The page-template.php files are in a folder called "templates", and that is set correctly when initializing the Templater.

Can anyone else replicate this issue? Or see if they have success getting the script to work?

**Comment by dschiera95** [comment]
I had this issue. I am using WordPress 5.2.4.
I believe it may have to do with how Gutenberg editor is using the REST API to update the post. 
https://github.com/mohamdio/wp-templater/blob/256edf3e7489c93250676805c4f8584a86a84af9/src/Templater.php#L251-L251
The call to `get_post_type()` is returning post when you are using a Custom Post Type.
The fix is to use the $current_post_type variable that is available as part of the `theme_{$post_type}_filter` filter.

**Comment by mohamdio** [comment]
#Fixed
